# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param simulator.modelsimInstallPath D:/modeltech64_2019.2/win64
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/paste/V1.3.cache/wt [current_project]
set_property parent.project_path D:/Users/paste/V1.3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo d:/Users/paste/V1.3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Users/paste/rom_4096.coe
read_verilog -library xil_defaultlib {
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/add_3_3.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/chan_1.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/channel1_to_fft.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/channel2_to_fft.v
  D:/Users/paste/V1.3.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/div.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/extract_time_top.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/fft_multiplier_ifft.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/ifft.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/int32_to_float.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/inv.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/martix_multip.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/matrix_tran.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/multip_3_3.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/pinv.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/rom.v
  D:/Users/paste/V1.3.srcs/sources_1/imports/new/top.v
}
add_files D:/Users/paste/V1.3.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Users/paste/V1.3.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/cmpy_0/cmpy_0.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/cmpy_0/cmpy_0_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_2/floating_point_2.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_2/floating_point_2_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_3/floating_point_3.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_3/floating_point_3_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_4/floating_point_4.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_4/floating_point_4_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_5/floating_point_5.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/floating_point_5/floating_point_5_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/ifft_1/ifft_1.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/ifft_1/ifft_1_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/xfft_0/xfft_0_ooc.xdc]

read_ip -quiet d:/Users/paste/V1.3.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Users/paste/V1.3.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/paste/V1.3.srcs/constrs_1/new/SDC.xdc
set_property used_in_implementation false [get_files D:/Users/paste/V1.3.srcs/constrs_1/new/SDC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
